"""
Factory Router

End-to-end video generation pipeline.
"""

from fastapi import APIRouter, Depends
from app.core.interfaces import IContentProvider, IAIProvider, ITTSProvider, IVideoProvider, IUploadProvider
from app.core.plugin_loader import PluginLoader
from app.core.logger import log_step, log_success, console
from pydantic import BaseModel

router = APIRouter()


# Dependencies
def get_content_provider() -> IContentProvider:
    return PluginLoader.load("content")

def get_ai_provider() -> IAIProvider:
    return PluginLoader.load("ai")

def get_tts_provider() -> ITTSProvider:
    return PluginLoader.load("tts")

def get_video_provider() -> IVideoProvider:
    return PluginLoader.load("video")

def get_upload_provider() -> IUploadProvider:
    return PluginLoader.load("upload")


class VideoRequest(BaseModel):
    content_limit: int = 1
    upload: bool = False


@router.post("/generate")
async def generate_video(
    request: VideoRequest,
    content_provider: IContentProvider = Depends(get_content_provider),
    ai_provider: IAIProvider = Depends(get_ai_provider),
    tts_provider: ITTSProvider = Depends(get_tts_provider),
    video_provider: IVideoProvider = Depends(get_video_provider),
    upload_provider: IUploadProvider = Depends(get_upload_provider)
):
    """
    Generate a complete video from content → script → audio → video → upload.
    
    This demonstrates the full plugin pipeline!
    All providers are injected based on config.yaml.
    """
    
    console.print("\n[bold cyan]🎬 Starting Video Generation Pipeline[/bold cyan]\n")
    
    # Step 1: Fetch content
    log_step("Step 1/5: Fetching Content")
    items = await content_provider.fetch_content(limit=request.content_limit)
    
    if not items:
        return {"error": "No content fetched"}
    
    content_item = items[0]
    log_success(f"Got content: {content_item.title[:50]}...")
    
    # Step 2: Generate script with AI
    log_step("Step 2/5: Generating Script (AI)")
    script = await ai_provider.generate_script(content_item)
    log_success(f"Script generated by {ai_provider.get_provider_name()}")
    
    # Step 3: Text-to-Speech
    log_step("Step 3/5: Converting to Speech (TTS)")
    audio = await tts_provider.text_to_speech(script.full_script)
    log_success(f"Audio: {audio.duration:.1f}s by {tts_provider.get_provider_name()}")
    
    # Step 4: Assemble video
    log_step("Step 4/5: Assembling Video")
    video = await video_provider.assemble_video(
        audio_path=audio.path,
        script=script.full_script
    )
    log_success(f"Video created: {video.path}")
    
    # Step 5: Upload (optional)
    upload_result = None
    if request.upload:
        log_step("Step 5/5: Uploading")
        upload_result = await upload_provider.upload(
            video_path=video.path,
            title=content_item.title,
            description=script.full_script,
            tags=["shorts", "viral"]
        )
        log_success(f"Uploaded to {upload_provider.get_platform_name()}")
    
    console.print("\n[bold green]✅ Pipeline Complete![/bold green]\n")
    
    return {
        "status": "success",
        "content": {
            "id": content_item.id,
            "title": content_item.title,
            "source": content_item.source
        },
        "script": {
            "hook": script.hook,
            "provider": script.provider
        },
        "audio": {
            "path": audio.path,
            "duration": audio.duration
        },
        "video": {
            "path": video.path,
            "duration": video.duration
        },
        "upload": upload_result,
        "providers_used": {
            "content": content_provider.config.provider,
            "ai": ai_provider.get_provider_name(),
            "tts": tts_provider.get_provider_name(),
            "video": video_provider.config.provider,
            "upload": upload_provider.get_platform_name() if request.upload else "skipped"
        }
    }


@router.get("/config")
async def get_active_config():
    """Show currently active providers."""
    from app.core.config import get_settings
    settings = get_settings()
    
    return {
        "providers": {
            "content": settings.content.provider,
            "ai": settings.ai.provider,
            "tts": settings.tts.provider,
            "video": settings.video.provider,
            "upload": settings.upload.provider,
            "database": settings.database.provider
        }
    }
